Blogg/Models/category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Blogg.Models
{
    public class category
    {
        public int categoryID { get; set; }
        public string categoryTitle { get; set; }
    }
}

Blogg/Models/post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Blogg.Models
{
    public class post
    {
        public int postID { get; set; }
        [MaxLength(50, ErrorMessage ="Max lengt 50 charakters")]
        [Required(ErrorMessage = "Måste ha en titel")]
        public string postTitle { get; set; }
        [MaxLength(2000)]
        public string postBody { get; set; }
        public string categoryName { get; set; }
        public DateTime postDate { get; set; }
    }
}

Blogg/Controllers/BlogPostsController.cs
using Blogg.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blogg.Controllers
{
    public class BlogPostsController : Controller
    {
        Blogcontext context = new Blogcontext();
        // GET: BlogPosts
        public ActionResult Index(string Type,string sort)
        {
            
            var allposts = context.posts.ToList();

            if (Type == null)
            {
                ViewData["DisplayAs"] = "normal";
            } else if(Type == "list")
            {
                ViewData["DisplayAs"] = "list";
            } else
            {
                ViewData["DisplayAs"] = "normal";
            }

            if (sort == "ASC")
            {
                allposts = context.posts.OrderBy(x => x.postDate).ToList();
            }
            else if (sort == "DESC")
            {
                allposts = context.posts.OrderByDescending(x => x.postDate).ToList();
            }
            ViewBag.categories = context.categories.Select(x => x.categoryTitle);


            return View(allposts);
        }
        public ActionResult Delete(int id)
        {
            var post = context.posts.SingleOrDefault(x => x.postID == id);
            context.posts.Remove(post);
            context.SaveChanges();
            return View(post);
        }
        public ActionResult ViewPost(int id)
        {
            var post = context.posts.Where(x => x.postID == id).ToList();
            return View(post);
        }
        public ActionResult search(string word)
        {
            Blogcontext context = new Blogcontext();
            var allposts = context.posts.Where(x => x.postTitle.Contains(word)).ToList();
            ViewBag.categories = context.categories.Select(x => x.categoryTitle);
            ViewData["DisplayAs"] = "list";

            return View("~/Views/BlogPosts/Index.cshtml", allposts);
        }
        [HttpGet]
        public ActionResult Create()
        {
            var catnames = context.categories.Select(x => x.categoryTitle).ToList();
            ViewBag.categories = catnames;
            return View(new post());

        }
        [HttpPost]
        public ActionResult Create(post Post)
        {
            if (ModelState.IsValid)
            {
                Post.postDate = DateTime.Now;
                context.posts.Add(Post);
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            {
                return View("~/Views/BlogPosts/Create.cshtml", Post);
            }
        }
    }

}

Blogg/Controllers/HomeController.cs
using Blogg.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blogg.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            Blogcontext context = new Blogcontext();
            var allcategories = context.categories.ToList();

            if(!context.categories.Any()){
                var cates = new List<category>()
                {
                    new category {categoryID = 1, categoryTitle = "Action" },
                    new category {categoryID = 2, categoryTitle = "Drama" },
                    new category {categoryID = 3, categoryTitle = "Komedi" },
                    new category {categoryID = 4, categoryTitle = "Skräck" }
                };
                foreach (var c in cates)
                {
                    context.categories.Add(c);
                }
                context.SaveChanges();
            }

            return View(allcategories);
        }
    }
}

Blogg/Views/BlogPosts/Create.cshtml
@model Blogg.Models.post

@{
    ViewBag.Title = "Lägg till film";
    Layout = "~/Views/shared/_Layout.cshtml";
}

<h2>Lägg till ny film</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            <label class="col-md-2 control-label">Titel</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.postTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.postTitle, null, new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-2 control-label">Beskrivning</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.postBody, new { @class = "form-control", @rows = 10 })
                @Html.ValidationMessageFor(model => model.postBody, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label">Kategori</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.categoryName, new SelectList(ViewBag.categories), new { @class = "form-control" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tilbaka till listan", "Index")
</div>

Blogg/Views/BlogPosts/Delete.cshtml
@model Blogg.Models.post

@{
    ViewBag.Title = "Ta bort";
    Layout = "~/Views/shared/_Layout.cshtml";
}

<h2>Ta bort</h2>

<h3>Denna post har blivit borttagen</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Namn
        </dt>

        <dd>
            @Html.DisplayFor(model => model.postTitle)
        </dd>

        <dt>
            Beskrivning
        </dt>

        <dd>
            @Html.DisplayFor(model => model.postBody)
        </dd>

        <dt>
            Kategori
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoryName)
        </dd>

        <dt>
            Datum
        </dt>

        <dd>
            @Html.DisplayFor(model => model.postDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Tilbaka till listan", "Index")
        </div>
    }
</div>

Blogg/Views/BlogPosts/Index.cshtml
@model IEnumerable<Blogg.Models.post>

@{
    ViewBag.Title = "Marres - Movies";
    Layout = "~/Views/shared/_Layout.cshtml";

}

<h1>Welcome to Marres - Movies</h1>

@using (Html.BeginForm("search","BlogPosts",FormMethod.Get))
{
    <div>
        <p class="pull-right"> 
            @Html.TextBox("word", "Sök text")
            <button value="Sök" id="searchButton" type="submit">Sök</button>
        </p>
    </div>
}

<p>
    @Html.ActionLink("Nytt inlägg", "Create", "BlogPosts")
    </p>
    <div align="center">
      @Html.ActionLink("DESC", "Index", "BlogPosts", new { sort = "DESC", Type = ViewData["DisplayAs"].ToString() }, null)
      @Html.ActionLink("ASC", "Index", "BlogPosts", new { sort = "ASC", Type = ViewData["DisplayAs"].ToString() }, null)
    </div>
<div align="left">
    @Html.ActionLink("Normal", "Index", "BlogPosts", new { Type = "normal" }, null)
    @Html.ActionLink("List", "Index", "BlogPosts", new { Type = "list" }, null)
</div>
 @foreach (var item in ViewBag.categories)
 {
 @item @Html.Raw("&nbsp;")
 }

        <div>
    @if (Model.Count() == 0)
    {
        <text> din sökning gav inga resultat</text>
    }
    @if ((ViewData["DisplayAs"].ToString() == "normal"))
            {
        foreach (var item in Model)
                {
            <div class="panel panel-default">
                <div class="panel-heading">

                    <div class="row" id="HeaderRow">
                        <div class="col-xs-8">
                            @Html.DisplayFor(modelItem => item.postTitle)
                        </div>
                        <div class="col-xs-4">
                            @Html.DisplayFor(modelItem => item.postDate)
                        </div>
                    </div>
                </div>
                <div class="panel-body panelBodyText">
                    <pre>@Html.DisplayFor(modelItem => item.postBody)</pre>
                    <div align="right">@Html.ActionLink("Ta bort", "Delete", new { id = item.postID })</div>
                </div>
                <div class="panel-footer">
                        <div class="w3-btn w3-blue-grey w3-hover-blue">@Html.DisplayFor(modelItem => item.categoryName)</div>
                </div>
            </div>
                <hr />
        }
    }
    <div>
        @if ((ViewData["DisplayAs"].ToString() == "list")) //kollar ifall list mode is on
            {
                foreach (var item in Model)
                {

                <div class="panel panel-default">
                <div class="panel-heading">

                    <div class="row" id="HeaderRow">
                        <div class="col-xs-8">
                            @Html.DisplayFor(modelItem => item.postTitle)
                        </div>
                        <div class="col-xs-4">
                            @Html.DisplayFor(modelItem => item.postDate)
                        </div>
                    </div>
                </div>
                <div class="panel-body panelBodyText">
                    <pre>@Html.ActionLink("Visa", "ViewPost", new { id = item.postID })</pre>
                </div>
                <div class="panel-footer">
                </div>
            </div>
                <hr />
                
            }
        }
        </div>
</div>

Blogg/Views/BlogPosts/ViewPost.cshtml
@model IEnumerable<Blogg.Models.post>

@{
    ViewBag.Title = "View";
    Layout = "~/Views/shared/_Layout.cshtml";
}

<h2>Inlägg</h2>

<div>
    @foreach (var item in Model)
    {
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Namn
        </dt>

        <dd>
            @Html.DisplayFor(model => item.postTitle)
        </dd>

        <dt>
            Datum
        </dt>

        <dd>
            @Html.DisplayFor(model => item.postDate)
        </dd>

        <dt>
            Kategori
        </dt>

        <dd>
            @Html.DisplayFor(model => item.categoryName)
        </dd>

        <dt>
            Beskrivning
        </dt>

        <dd>
            @Html.DisplayFor(model => item.postBody)
        </dd>

    </dl>
    }

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Tilbaka till listan", "Index")
        </div>
    }
</div>

Blogg/Views/Home/Index.cshtml
@model IEnumerable<Blogg.Models.category>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/shared/_Layout.cshtml";
}

<h2>Marres - Movies</h2>
<img src="~/Content/movies.jpg" alt="">
<table class="table">
    <tr>
        <th>
            Kategorier vi täcker
        </th>
        <th></th>
    </tr>
    <tr>
        <td>
            @foreach (var item in Model)
            {
                @Html.DisplayFor(modelItem => item.categoryTitle) @Html.Raw("&nbsp;")
            }
        </td>
    </tr>
</table>

Blogg/Views/shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Hem", "Index", "Home")</li>
                    <li>@Html.ActionLink("Blogg", "Index", "BlogPosts")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Marres Movies</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>